config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :tasks
  resources :domains

  get 'fill_up_titles' => 'tasks#fill_up_titles'
  get 'fill_up_domains' => 'domains#fill_up_domains'
  get 'add_nums' => 'domains#add_nums'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class Domain_obj
  attr_reader :num,
              :request,
              :domain,
              :domain_length,
              :consonants_m3,
              :url_len_med,
              :title_len_med,
              :slashes_med,
              :req_dom_pgs,
              :req_dom_url,
              :direct_phones,
              :has800,
              :total_phones,
              :has_about_page,
              :has_contact_page,
              :has_social,
              :commun_methods,
              :own_email,
              :has_sale,
              :title_in_body

  def initialize(num, request, domain, domain_length, consonants_m3, url_len_med,
                title_len_med, slashes_med, req_dom_pgs, req_dom_url,
                direct_phones, has800, total_phones, has_about_page,
                has_contact_page, has_social, commun_methods, own_email,
                has_sale, title_in_body)
    @num              = num
    @request          = request
    @domain           = domain
    @domain_length    = domain_length
    @consonants_m3    = consonants_m3
    @url_len_med      = url_len_med
    @title_len_med    = title_len_med
    @slashes_med      = slashes_med
    @req_dom_pgs      = req_dom_pgs
    @req_dom_url      = req_dom_url
    @direct_phones    = direct_phones
    @has800           = has800
    @total_phones     = total_phones
    @has_about_page   = has_about_page
    @has_contact_page = has_contact_page
    @has_social       = has_social
    @commun_methods   = commun_methods
    @own_email        = own_email
    @has_sale         = has_sale
    @title_in_body    = title_in_body
  end
end

class DomainsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.xls { send_data xls_grouper, filename: "#{Rails.root}/public/domains.xls" }
    end
  end

  def create
    attachment = task_params[:attachment]
    File.open(Rails.root.join('public', 'uploads', attachment.original_filename), 'wb') do |file|
      file.write(attachment.read)
    end
    ImportDomainsWorker.perform_async attachment.original_filename
    respond_to do |format|
      format.html { render :index }
      format.js { render :create }
    end
  end

  def fill_up_domains
    DomainCheckWorker.perform_async
  end

  def add_nums
    AddNumsWorker.perform_async
  end

  private

  def task_params
    params.require(:domain).permit(:attachment)
  end

  def xls_grouper
    domains = Domain.all.order(:request, :num)
    domains.to_xls(
        cell_format: {
          weight:           :bold,
          bottom_color:     :green,
          left:             :dotted,
          right:            :dashed,
          top:              :dotted,
          bottom:           :dashed,
          horizontal_align: :left,
          font: Spreadsheet::Font.new('Courier New', color: :blue)
        },
        header_format: {
          weight: :bold,
          color:  :black,
          right:  :dashed,
          bottom: :double,
          diagonal_color: :red,
          pattern_fg_color: :red,
          pattern_bg_color: :border,
          cross_down: true
        },
        column_width: { [:requests] => 40 },
        columns: [
          :num,
          :request,
          :domain,
          :domain_length,
          :consonants_m3,
          :url_len_med,
          :title_len_med,
          :slashes_med,
          :req_dom_pgs,
          :req_dom_url,
          :direct_phones,
          :has800,
          :total_phones,
          :has_about_page,
          :has_contact_page,
          :has_social,
          :commun_methods,
          :own_email,
          :has_sale,
          :title_in_body
        ],
        headers: [
          '№',
          'Фраза',
          'Домен',
          'Длина домена в символах',
          'Количество 3 согласных идущих подряд в названии домена',
          'Средняя длина (медиана) url в символах',
          'Средняя длина TITLE (медиана)',
          'Среднее количество слешей',
          'Количество страниц сайта по данному запросу [запрос site:domen.ru]',
          'URL сайта по этому запросу',
          'количестов прямых номеров телефона',
          'есть ли 8-800',
          'сколько всего номеров телефонов есть на странице (разные вариации)',
          'есть ли страница О КОМПАНИИ',
          'Есть ли страница КОНТАКТЫ',
          'есть ли кнопки соцсетей (ссылки на них) или плагины шаринга (tech.yandex.ru/share)',
          'кол-во способов связи (вытаскиваем со страницы: скайп, почта, обратный звонок. обратная связь, онлайн консультант, городской\мобильный телефон , несколько телефонов)',
          'почта на своем домене есть/нет',
          'Наличие слов СКИДКА АКЦИИ РАСПРОДАЖА SALE и других на странице в h1-h6 или ссылках',
          'Все слова в title встречаются хотя бы 1 раз на странице'
        ]
    ).force_encoding('UTF-8')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
  end

  def create
    attachment = task_params[:attachment]
    File.open(Rails.root.join('public', 'uploads', attachment.original_filename), 'wb') do |file|
      file.write(attachment.read)
    end
    ImportWorker.perform_async attachment.original_filename
    respond_to do |format|
      format.html { render :index }
      format.js { render :create }
    end
  end

  def fill_up_titles
    TitleFetchWorker.perform_async
  end

  def export
    respond_to do |format|
      format.html
      format.xls { send_data xls_grouper(params[:id], @my_site_present, @grouping.requesting_id), filename: "#{Rails.root}/public/task_#{params[:id]}.xls" }
      format.csv { render_csv(params[:id]) }
    end
  end

  private

  def task_params
    params.require(:task).permit(:attachment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domain_helper.rb
module DomainHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/domains/add_nums.js.erb
alert('add_nums: OK');

app/views/domains/create.js.erb
$("#domain_name").val("");
$("#launch").prop("disabled", true);
$("#status").text("Задача успешно запущена");

app/views/domains/error.js.erb
alert("<%= @error %>");

app/views/domains/fill_up_domains.js.erb
alert('OK');

app/views/domains/index.html.slim
.green
  => link_to 'К title', tasks_path
  = link_to 'Экспорт в xls', domains_path(format: :xls)
  = form_for :domain, html: { multipart: true }, remote: true do |f|
    span Выбрать файл
    = f.file_field :attachment
    = f.submit 'Запуск', id: 'launch'
  p#status Статус
  => link_to 'Собрать domains', fill_up_domains_path, remote: true
  = link_to 'Добавить номера', add_nums_path, remote: true

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="turbolinks-cache-control" content="no-preview"
    title ComParser
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/tasks/create.js.erb
$("#task_name").val("");
$("#launch").prop("disabled", true);
$("#status").text("Задача успешно запущена");

app/views/tasks/error.js.erb
alert("<%= @error %>");

app/views/tasks/fill_up_titles.js.erb
alert('OK');

app/views/tasks/index.html.slim
.violet
  => link_to 'К доменам', domains_path
  = link_to 'Экспорт в xls', tasks_path(format: :xls)
  = form_for :task, html: { multipart: true }, remote: true do |f|
    span Выбрать файл
    = f.file_field :attachment
    = f.submit 'Запуск', id: 'launch'
  p#status Статус
  = link_to 'Собрать title', fill_up_titles_path, remote: true